export const STRIPE_CHECKOUT_TTL_EXACT_MS = 10 * 60 * 1000;
export const DEFAULT_STRIPE_CHECKOUT_TTL_MS = STRIPE_CHECKOUT_TTL_EXACT_MS;
export const STRIPE_CHECKOUT_MIN_EXPIRES_IN_SECONDS = 30 * 60;
export const CHECKOUT_MAX_LINE_ITEMS = 50;
